language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install pylint"
script:
  - "pylint --errors-only demand.py"
addons:
  ssh_known_hosts: blackleg.es
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    repo: blackleg/web
    branch: master